# Generated by Django 5.2.1 on 2025-06-10 18:06

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="forms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=30)),
                ("user_phone", models.CharField(max_length=12)),
                ("user_message", tinymce.models.HTMLField()),
            ],
        ),
    ]
