# Generated by Django 5.2.1 on 2025-06-10 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fm", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forms",
            old_name="user_name",
            new_name="user_email",
        ),
    ]
