# Generated by Django 5.2.1 on 2025-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fm", "0002_rename_user_name_forms_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="forms",
            name="user_name",
            field=models.CharField(default="ahmad", max_length=20),
        ),
    ]
