# Generated by Django 5.2.1 on 2025-06-08 18:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_title", models.CharField(max_length=23)),
                ("car_desc", tinymce.models.HTMLField()),
                ("car_line", models.CharField(verbose_name=200)),
            ],
        ),
    ]
