# Generated by Django 5.2.1 on 2025-06-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="car_line",
            field=models.CharField(max_length=200),
        ),
    ]
