# Generated by Django 5.2.1 on 2025-06-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0002_alter_card_car_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="newcar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_new_title", models.CharField(max_length=12)),
                ("car_new_des", models.CharField(max_length=500)),
            ],
        ),
    ]
